version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.9-gatsby
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        DISABLE_PRISMA_TELEMETRY: true
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            host: aws-0-eu-west-2.pooler.supabase.com
            port: 6543
            user: postgres.msuopbjhcutdvsvqmxnp
            password: ${DB_PASSWORD}
            connectionLimit: 10
